parameters:
  - name: subscription
    type: string

  - name: environment
    type: string

  - name: builtFrom
    type: string
    default: ''

  - name: businessArea
    type: string
    default: ''

  - name: displayName
    type: string

  - name: dependsOn
    type: string

jobs:
- job: setupAzureMonitorLink
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
    - template: templates\Azure\Monitor\link.yaml@azTemplates
      parameters:
        subscription: ${{ parameters.subscription }}
        appName: "hearing-management-interface"
        appPrefix: "hmi"
        businessArea: ${{ parameters.businessArea }}
        builtFrom: ${{ parameters.builtFrom }}
        environment: ${{ parameters.environment }} 
        logAnalyticsResourceGroup: $(la-rg)
        logAnalyticsSubscriptionId: $(log_analytics_subscription_id)
        resourceGroupName: 'hmi-sharedinfra-${{ parameters.environment }}-rg'
