parameters:
  - name: subscription
    type: string

  - name: environment
    type: string

  - name: builtFrom
    type: string
    default: ''

  - name: businessArea
    type: string
    default: 'Cross-Cutting'

  - name: product
    type: string
    default: ''

  - name: displayName
    type: string

  - name: dependsOn
    type: string

jobs:
- job: setupAzureMonitorLink
  dependsOn:
  - ${{ if parameters.dependsOn }}:
    - ${{ parameters.dependsOn }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - task: AzurePowerShell@5
    inputs:
      azureSubscription: ${{ parameters.subscription }}
      ScriptType: 'FilePath'
      ScriptPath: '$(System.DefaultWorkingDirectory)/pipeline/scripts/azmonlink.ps1'
      ScriptArguments: '-businessArea ${{ parameter.businessArea }} -product ${{ parameters.product}} -builtFrom ${{ parameters.builtFrom }} -environment ${{ parameters.environment }} -larg $(la-rg) -lasboxsubid $(la-sbox-sub-id) -lanonprodsubid $(la-nonprod-sub-id) -laprodsubid $(la-prod-sub-id)'
      azurePowerShellVersion: 'LatestVersion'
