parameters:
  - name: subscription
    type: string

  - name: environment
    type: string

  - name: builtFrom
    type: string
    default: ''

  - name: businessArea
    type: string
    default: ''

  - name: product
    type: string
    default: ''

  - name: location
    type: string
    default: uksouth

  - name: displayName
    type: string

  - name: dependsOn
    type: string
    default: ''

jobs:
- job: setupInfrastructure
  dependsOn:
  - ${{ if parameters.dependsOn }}:
    - ${{ parameters.dependsOn }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - template: ../steps/create-rg.yaml
    parameters:
      subscription: ${{ parameters.subscription }}
      resourceGroup: hmi-sharedinfra-${{ parameters.environment }}-rg
      storageAccount: hmiapiminfra${{ parameters.environment }}sa
      policiesAccount: hmiapimpolicies${{ parameters.environment }}sa
      location: ${{ parameters.location }}
      environment: ${{ parameters.environment }}
      builtFrom: ${{ parameters.builtFrom }}
      product: ${{ parameters.product }}
      businessArea: ${{ parameters.businessArea }}

  - template: ../steps/set_kv_permissions.yaml
    parameters:
      subscription: ${{ parameters.subscription }}
      environment: ${{ parameters.environment }}