parameters:
  - name: subscription
    type: string

  - name: environment
    type: string

  - name: builtFrom
    type: string
    default: ''

  - name: businessArea
    type: string
    default: ''

  - name: application
    type: string
    default: ''

  - name: location
    type: string
    default: uksouth

  - name: displayName
    type: string

  - name: dependsOn
    type: string
    default: ''
  
  - name: resourceGroupName
    type: string
  - name: storageAccount
    type: string
  - name: containerName
    type: string
  - name: resourcePrefix
    type: string

jobs:
- job: setupInfrastructure
  dependsOn:
  - ${{ if parameters.dependsOn }}:
    - ${{ parameters.dependsOn }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - template: ../steps/create-rg.yaml
    parameters:
      subscription: ${{ parameters.subscription }}
      resourceGroup: ${{ parameters.resourceGroupName }}
      storageAccount: ${{ parameters.storageAccount }}
      containerName: ${{ parameters.containerName }}
      policiesAccount: ${{ parameters.resourcePrefix }}policies${{ parameters.environment }}sa
      location: ${{ parameters.location }}
      environment: ${{ parameters.environment }}
      builtFrom: ${{ parameters.builtFrom }}
      businessArea: ${{ parameters.businessArea }}
      application: ${{ parameters.application }}

  - template: ../steps/set_kv_permissions.yaml
    parameters:
      subscription: ${{ parameters.subscription }}
      environment: ${{ parameters.environment }}