parameters:
  - name: fileName
    type: string

  - name: environmentName
    type: string
    
  - name: displayName
    type: string 

jobs:
- job: setupVariableGroups
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: 'ubuntu-latest'

  steps:
    - task: Bash@3
      inputs:
        filePath: $(System.DefaultWorkingDirectory)/pipeline/scripts/update_variable_groups.sh
        arguments: $(devopsUser), $(devopsPAT)
        workingDirectory: $(System.DefaultWorkingDirectory)/environments
