parameters:
  - name: subscription
    type: string

  - name: dependsOn
    type: string

  - name: resourceGroup
    type: string

  - name: location
    type: string
    default: uksouth

  - name: storageAccount
    type: string

  - name: containerName
    type: string

  - name: variables
    type: object

  - name: displayName
    type: string

  - name: environment
    type: string

  - name: builtFrom
    type: string
    default: ''

  - name: productName
    type: string
    default: ''

jobs:
- job: Terraform
  dependsOn:
  - ${{ if parameters.dependsOn }}:
    - ${{ parameters.dependsOn }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: 'ubuntu-20.04'
  variables:
    ${{ insert }}: ${{ parameters.variables }}
  steps:
  - template: ../steps/tf-install.yaml
  - template: ../steps/tf-test.yaml
  - template: ../steps/tf-init.yaml
    parameters:
      subscription: ${{ parameters.subscription }}
      environment: ${{ parameters.environment }}
      resourceGroup: $(resourceGroup)
      storageAccount: $(storageAccount)
      containerName: $(containerName)
  - template: ../steps/tf-plan.yaml
    parameters:
      subscription: ${{ parameters.subscription }}
      resourceGroup: $(resourceGroup)
      environment: ${{ parameters.environment }}
      builtFrom: ${{ parameters.builtFrom }}
      productName: ${{ parameters.productName }}
  - template: ../steps/tf-apply.yaml
    parameters:
      subscription: ${{ parameters.subscription }}
      environment: ${{ parameters.environment }}