parameters:
  - name: subscription
    type: string

  - name: dependsOn
    type: string

  - name: resourceGroup
    type: string

  - name: storageAccount
    type: string

  - name: containerName
    type: string

  - name: variables
    type: object

  - name: displayName
    type: string

  - name: environment
    type: string

  - name: builtFrom
    type: string
    default: ''

  - name: product
    type: string
    default: ''

  - name: outputName
    type: string

  - name: waitForValidation
    type: boolean
    default: true

jobs:
- job: Terraform
  dependsOn:
  - ${{ if parameters.dependsOn }}:
    - ${{ parameters.dependsOn }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: 'ubuntu-20.04'
  variables:
    ${{ insert }}: ${{ parameters.variables }}
  steps:
  - template: ../steps/tf-install.yaml
  - template: ../steps/tf-init.yaml
    parameters:
      subscription: ${{ parameters.subscription }}
      environment: ${{ parameters.environment }}
      resourceGroup: $(resourceGroup)
      storageAccount: $(storageAccount)
      containerName: $(containerName)
  - template: ../steps/tf-plan.yaml
    parameters:
      subscription: ${{ parameters.subscription }}
      resourceGroup: $(resourceGroup)
      environment: ${{ parameters.environment }}
      builtFrom: ${{ parameters.builtFrom }}
      product: ${{ parameters.product }}
      outputLocation: '$(Build.SourcesDirectory)/plans/${{ environment.name }}/${{ parameters.outputName }}.tfplan'
  
  - task: PublishPipelineArtifact@1
    displayName: 'Publish Terraform Plan'
    inputs:
      targetPath: ${{ parameters.outputLocation }}
      artifact: '${{ parameters.environment }}/${{ parameters.outputName }}.tfplan'

  - ${{ if eq('${{parameters.waitForValidation}}','true')}}:
    - template: ../steps/wait.yml
      parameters:
        environment: ${{ parameters.environment }}