parameters:
  - name: subscription
    type: string

  - name: dependsOn
    type: string
    default: '[]'

  - name: resourceGroup
    type: string

  - name: location
    type: string
    default: uksouth

  - name: storageAccount
    type: string

  - name: containerName
    type: string

  - name: variables
    type: object

  - name: displayName
    type: string

  - name: environment
    type: string

  - name: builtFrom
    type: string
    default: ''

  - name: product
    type: string
    default: ''

  - name: outputName
    type: string

  - name: workingDirectory
    type: string

jobs:
- job: Terraform
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: 'ubuntu-20.04'
  variables:
    ${{ insert }}: ${{ parameters.variables }}
  steps:
  - download: current
    artifact: '${{ parameters.outputName }}'
    displayName: 'Download ${{ parameters.outputName }}.tfplan'
  - template: ../steps/tf-install.yaml
  - bash: |
      echo "Resource Group: ${{ variables.resourceGroup }}"
      echo "Storage Account: ${{ variables.storageAccount }}"
      echo "Container Name: ${{ variables.containerName }}"
  - template: ../steps/tf-init.yaml
    parameters:
      subscription: ${{ parameters.subscription }}
      environment: ${{ parameters.environment }}
      resourceGroup: ${{ variables.resourceGroup }}
      storageAccount: ${{ variables.storageAccount }}
      containerName: ${{ variables.containerName }}
      workingDirectory: ${{ parameters.workingDirectory }}

  
  - bash: |
      mkdir '$(Build.SourcesDirectory)/certs'
    displayName: Create Certificates directory
  - template: ../steps/az-download-pfx.yaml
    parameters:
      subscriptionName: ${{ parameters.subscription }}
      sourceKvName: "$(source_kv_name_prefix)-${{ parameters.environment }}"
      sourceCertName: $(source_cert_name)
      environment: ${{ parameters.environment }}
      targetpath: "$(Build.SourcesDirectory)/certs/${{ parameters.environment }}.pfx"
  - template: ../steps/az-purge-deleted-cert.yaml
    parameters:
      subscriptionName: ${{ parameters.subscription }}
      kvName: "hmi-shared-kv-${{ parameters.environment }}"
      certName: "star-sandbox"



  - template: ../steps/tf-apply.yaml
    parameters:
      subscription: ${{ parameters.subscription }}
      environment: ${{ parameters.environment }}
      workingDirectory: ${{ parameters.workingDirectory }}
      planLocation: '$(Pipeline.Workspace)/${{parameters.outputName}}/${{parameters.outputName}}.tfplan'