parameters:
  - name: subscription
    type: string

  - name: stateResourceGroup
    type: string

  - name: location
    type: string

  - name: storageAccount
    type: string

  - name: containerName
    type: string

  - name: environment
    type: string

  - name: builtFrom
    type: string

  - name: product
    type: string

  - name: outputName
    type: string

  - name: workingDirectory
    type: string

jobs:
- job: Terraform
  displayName: "Deploy ${{ parameters.environment }} Shared Infra"
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - download: current
    artifact: '${{ parameters.outputName }}'
    displayName: 'Download ${{ parameters.outputName }}.tfplan'
    
  - template: ../steps/tf-install.yaml

  - template: ../steps/tf-init.yaml
    parameters:
      subscription: ${{ parameters.subscription }}
      environment: ${{ parameters.environment }}
      stateResourceGroup: ${{ parameters.stateResourceGroup }}
      storageAccount: ${{ parameters.storageAccount }}
      containerName: ${{ parameters.containerName }}
      workingDirectory: ${{ parameters.workingDirectory }}

  - template: ../steps/tf-variables.yaml
    parameters:
      variableName: "varValue"
      environment: ${{ parameters.environment }}
      builtFrom: ${{ parameters.builtFrom }}
      product: ${{ parameters.product }}
      outputLocation: '$(Build.SourcesDirectory)/plans/${{ parameters.outputName }}.tfplan'
      subscriptionName: ${{ parameters.subscription }}

  - template: ../steps/tf-apply.yaml
    parameters:
      subscription: ${{ parameters.subscription }}
      environment: ${{ parameters.environment }}
      workingDirectory: ${{ parameters.workingDirectory }}
      planLocation: '$(Pipeline.Workspace)/${{parameters.outputName}}/${{parameters.outputName}}.tfplan'