parameters:
  - name: subscription
    type: string
  - name: stateResourceGroup
    type: string
  - name: storageAccount
    type: string
  - name: containerName
    type: string
  - name: environment
    type: string
  - name: builtFrom
    type: string
  - name: product
    type: string
  - name: outputName
    type: string
  - name: workingDirectory
    type: string

jobs:
- job: TerraformPlan
  dependsOn: setupInfrastructure
  displayName: "Plan ${{ parameters.environment }} Shared Infra"
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - template: ../steps/tf-install.yaml
  - template: ../steps/tf-init.yaml
    parameters:
      subscription: ${{ parameters.subscription }}
      environment: ${{ parameters.environment }}
      stateResourceGroup: ${{ parameters.stateResourceGroup }}
      storageAccount: ${{ parameters.storageAccount }}
      containerName: ${{ parameters.containerName }}
      workingDirectory: ${{ parameters.workingDirectory }}

  - bash: |
      mkdir '$(Build.SourcesDirectory)/plans'
    displayName: Create plan directory

  - template: ../steps/tf-variables.yaml
    parameters:
      variableName: "varValue"
      environment: ${{ parameters.environment }}
      builtFrom: ${{ parameters.builtFrom }}
      product: ${{ parameters.product }}
      outputLocation: '$(Build.SourcesDirectory)/plans/${{ parameters.outputName }}.tfplan'
      subscriptionName: ${{ parameters.subscription }}

  - template: ../steps/tf-plan.yaml
    parameters:
      subscription: ${{ parameters.subscription }}
      tfVariables: $(tfVariables.varValue)
      workingDirectory: ${{ parameters.workingDirectory }}
  
  - task: PublishPipelineArtifact@1
    displayName: 'Publish Terraform Plan'
    inputs:
      targetPath: '$(Build.SourcesDirectory)/plans/${{ parameters.outputName }}.tfplan'
      artifact: '${{ parameters.outputName }}'
      FileCopyOptions: '/xo'

  