parameters:
  - name: subscription
    type: string

  - name: dependsOn
    type: string

  - name: resourceGroup
    type: string

  - name: location
    type: string
    default: uksouth

  - name: storageAccount
    type: string

  - name: containerName
    type: string

  - name: variables
    type: object

  - name: displayName
    type: string
  
  - name: environmentName
    type: string

jobs:
- job: Terraform
  dependsOn:
  - ${{ if parameters.dependsOn }}:
    - ${{ parameters.dependsOn }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    ${{ insert }}: ${{ parameters.variables }}
  steps:
  - template: ../steps/tf-install.yaml
  # - template: ../steps/tf-init.yaml
  #   parameters:
  #     subscription: ${{ parameters.subscription }}
  #     environmentName: ${{ parameters.environmentName }}
  #     resourceGroup: $(resourceGroup)
  #     storageAccount: $(storageAccount)
  #     containerName: $(containerName)
  # - template: ../steps/tf-plan.yaml
  #   parameters:
  #     subscription: ${{ parameters.subscription }}
  #     resourceGroup: $(resourceGroup)
  #     environmentName: ${{ parameters.environmentName }}
  # - template: ../steps/tf-apply.yaml
  #   parameters:
  #     subscription: ${{ parameters.subscription }}
  #     environmentName: ${{ parameters.environmentName }}