parameters:
  - name: environments
    type: object

stages:
    - ${{ each environment in parameters.environments }}:

      - stage: 'Plan_SharedInfra_${{ environment.name }}'
        ${{ if eq(environment.dependency, 'CIBuild') }}:
          dependsOn: '${{ environment.dependency }}'
        ${{ if ne(environment.dependency, 'CIBuild') }}:
          dependsOn: 'Apply_SharedInfra_${{ environment.dependency }}'
        displayName: Plan ${{ environment.name }} Shared Infrastructure
        pool:
          vmImage: 'ubuntu-latest'
        variables: 
          - template: ../variables/Shared.yaml
            parameters:
              environment: ${{ environment }}
          - template: ../variables/SharedInfra.yaml
            parameters:
              environment: ${{ environment }}

        jobs:
        - template: ../jobs/setup-infra.yaml
          parameters:
            displayName: Set up ${{ environment.name }} infrastructure for APIM deployments
            subscription: ${{ environment.subscription }}
            environment: ${{ environment.name }}
            builtFrom: ${{ variables.builtFrom }}
            businessArea: ${{ variables.businessArea }}
            application: ${{ variables.product }}
            resourceGroupName: ${{ variables.resourceGroupName }}
            containerName: ${{ variables.containerName }}
            storageAccount: ${{ variables.storageAccount }}
            resourcePrefix: ${{ variables.serviceResourcePrefix }}

        - template: ../jobs/terraform-plan.yaml
          parameters:
            displayName: "Plan ${{ environment.name }} Shared Infra"
            dependsOn: setupInfrastructure
            subscription: ${{ environment.subscription }}
            environment: ${{ environment.name }}
            resourceGroup: $(resourceGroup)
            storageAccount: $(storageAccount)
            containerName: $(containerName)
            builtFrom: ${{ variables.builtFrom }}
            product: ${{ variables.product }}
            variables:
              resourceGroup: ${{ variables.resourceGroupName }}
              containerName: ${{ variables.containerName }}
              storageAccount: ${{ variables.storageAccount }}
            outputName: ${{ variables.planOutputName }}
            workingDirectory: ${{ variables.workingDirectory }}
            serviceName: ${{ variables.serviceName }}
