parameters:
  - name: environments
    type: object
  - name: services
    type: object

stages:
  - ${{ each service in parameters.services }}:
    - ${{ each environment in parameters.environments }}:

      - ${{ if or(ne(environment.name, 'sbox'), eq(service.name, 'SharedServies')) }}:
        - stage: 'Wait_${{ service.name }}_${{ environment.name }}'
          dependsOn: 'Plan_${{ service.name }}_${{ environment.name }}'
          displayName: Wait ${{ environment.name }} ${{ service.displayName }}

          jobs:
            - job: Wait
              displayName: "Wait for approval"
              pool: server
              steps:
                - template: ../steps/wait.yml
                  parameters:
                    environment: ${{ environment.name }}
