parameters:
  - name: environments
    type: object

stages:
    - ${{ each environment in parameters.environments }}:

      - ${{ if or(ne(environment.name, 'sbox'), eq(variables.serviceName, 'SharedServies'), eq(variables.serviceName, 'SharedInfra')) }}:
        - stage: 'Wait_${{ variables.serviceName }}_${{ environment.name }}'
          dependsOn: 'Plan_${{ variables.serviceName }}_${{ environment.name }}'
          displayName: Wait ${{ environment.name }} ${{ variables.serviceDisplayName }}
          pool:
            vmImage: 'ubuntu-latest'

          jobs:
            - job: Wait
              displayName: "Wait for approval"
              pool: server
              steps:
                - template: ../steps/wait.yml
                  parameters:
                    environment: ${{ environment.name }}
