parameters:
  - name: environments
    type: object

stages:
    - ${{ each environment in parameters.environments }}:

      - ${{ if or(ne(environment.name, 'sbox'), eq('SharedInfra', 'SharedInfra')) }}:
        - stage: 'Wait_SharedInfra_${{ environment.name }}'
          dependsOn: 'Plan_SharedInfra_${{ environment.name }}'
          displayName: Wait ${{ environment.name }} Shared Infrastructure
          pool:
            vmImage: 'ubuntu-latest'

          jobs:
            - job: Wait
              displayName: "Wait for approval"
              pool: server
              steps:
                - template: ../steps/wait.yml
                  parameters:
                    environment: ${{ environment.name }}
