variables:
  rg: 'hmi-sharedinfra-sbox-rg'
  location: 'uksouth'

steps:
- task: AzurePowerShell@5
  displayName: 'Azure PowerShell script: InlineScript'
  inputs:
    azureSubscription: 'DTS-SHAREDSERVICES-SBOX'
    ScriptType: InlineScript
    Inline: |
     # You can write your azure powershell scripts inline here. 
     # You can also pass predefined and custom variables to this script using arguments
     
     az aks create -g $(rg) -n hmiaks --location $(location) --generate-ssh-keys
     
     az mysql server create --resource-group $(rg) --name demoserver  --location $(location) --admin-user myadmin --admin-password  --sku-name GP_Gen5_2 --version 8.0  --ssl-enforcement disabled
     
     az mysql db create --resource-group $(rg) --server-name mydemoserver --name wpdatabase
     
     az mysql server firewall-rule create --resource-group $(rg) --server-name mydemoserver –-name allowanyazureIPs --start-ip-address 0.0.0.0 --end-ip-address 0.0.0.0
     
     az mysql server firewall-rule create --resource-group $(rg) --server-name mydemoserver –-name allowmyIP --start-ip-address   --end-ip-address 
     
    azurePowerShellVersion: LatestVersion