---
trigger:
  - master
pr:
  - none

parameters:
  - name: environments
    type: object
    default:
    - name: sbox
      subscription: DTS-SHAREDSERVICES-SBOX
    - name: dev
      subscription: DTS-SHAREDSERVICES-DEV
    - name: test
      subscription: DTS-SHAREDSERVICES-TEST
    - name: stg
      subscription: DTS-SHAREDSERVICES-STG
    - name: prod
      subscription: DTS-SHAREDSERVICES-PROD

variables:
  - group: HMI-APIM-Common
  - name: productName
    value: 'sds-platform'
  - name: builtFrom
    value: $(Build.Repository.Name)

stages:

- ${{ each environment in parameters.environments }}:

  - stage: ${{ environment.name }}
    ${{ if environment.condition }}:
      condition: ${{ environment.condition }}
    displayName: Build ${{ environment.name }}

    jobs:
    - template: pipeline/jobs/setup-infra.yaml
      parameters:
        displayName: Set up infrastructure for APIM deployments
        subscription: ${{ environment.subscription }}
        environment: ${{ environment.name }}
        builtFrom: ${{ variables.builtFrom }}
        productName: ${{ variables.productName }}

    - template: pipeline/jobs/terraform.yaml
      parameters:
        displayName: Build Infrastructure with Terraform
        dependsOn: setupInfrastructure
        subscription: ${{ environment.subscription }}
        environment: ${{ environment.name }}
        resourceGroup: $(resourceGroup)
        storageAccount: $(storageAccount)
        containerName: $(containerName)
        builtFrom: ${{ variables.builtFrom }}
        productName: ${{ variables.productName }}
        variables:
          resourceGroup: $[dependencies.setupInfrastructure.outputs['setupResourceGroup.resourceGroup']]
          storageAccount: $[dependencies.setupInfrastructure.outputs['setupResourceGroup.storageAccount']]
          containerName: $[dependencies.setupInfrastructure.outputs['setupResourceGroup.containerName']]

    - template: pipeline/jobs/setup-azmonlink.yaml
      parameters:
        displayName: Set up Azure Monitor Link to Log Analytics
        dependsOn: Terraform
        subscription: ${{ environment.subscription }}
        environment: ${{ environment.name }}
