trigger:
  - master
pr:
  - none

resources:
  repositories:
    - repository: azTemplates
      type: github
      name: hmcts/azure-devops-templates
      ref: refs/heads/group-fixes
      endpoint: hmcts

parameters:
  - name: deployTo
    displayName: Services to Deploy (All default)
    type: string
    default: all-services
    values:
      - all-services
      - SharedInfra
      - SharedServies        

variables:
  - group: HMI-APIM-Common
  - name: product
    value: 'hmi'
  - name: businessArea
    value: 'Cross-Cutting'
  - name: builtFrom
    value: $(Build.Repository.Name)
  - name: application
    value: 'hearing-management-interface'

stages:

  - stage: CIBuild
    displayName: 'CI Build Application'
    jobs:
      - template: pipeline/jobs/terraform-validate.yaml
        parameters:
          displayName: "Validate Terraform files"

  - template: pipeline/stages/plan.yaml
    parameters:
      environments:
        - name: sbox
          subscription: DTS-SHAREDSERVICES-SBOX
          dependency: 'CIBuild'
        - name: dev
          subscription: DTS-SHAREDSERVICES-DEV
          dependency: 'sbox'
        - name: test
          subscription: DTS-SHAREDSERVICES-TEST
          dependency: 'dev'
        - name: stg
          subscription: DTS-SHAREDSERVICES-STG
          dependency: 'test'
        - name: prod
          subscription: DTS-SHAREDSERVICES-PROD
          dependency: 'stg'
      services: 
        - ${{ if or(eq("${parameters.deployTo", "all-services"}), eq("${parameters.deployTo", "SharedInfra"}))}}:
          - name: SharedInfra
            displayName: 'Shared Infrastructure'
            resourceGroupName: 'sharedinfra'
            resourcePrefix: 'hmiapim'
            terraformVersion: '0.13.3'
        - ${{ if or(eq("${parameters.deployTo", "all-services"}), eq("${parameters.deployTo", "SharedServies"}))}}:
          - name: SharedServies
            displayName: 'Shared Services'
            resourceGroupName: 'sharedservices-state'
            resourcePrefix: 'hmiss'
            terraformVersion: '0.15.4'

  - template: pipeline/stages/wait.yaml
    parameters:
      environments:
        - name: sbox
          subscription: DTS-SHAREDSERVICES-SBOX
          dependency: 'CIBuild'
        - name: dev
          subscription: DTS-SHAREDSERVICES-DEV
          dependency: 'sbox'
        - name: test
          subscription: DTS-SHAREDSERVICES-TEST
          dependency: 'dev'
        - name: stg
          subscription: DTS-SHAREDSERVICES-STG
          dependency: 'test'
        - name: prod
          subscription: DTS-SHAREDSERVICES-PROD
          dependency: 'stg'
      services: 
        - ${{ if or(eq("${parameters.deployTo", "all-services"}), eq("${parameters.deployTo", "SharedInfra"}))}}:
          - name: SharedInfra
            displayName: 'Shared Infrastructure'
            resourceGroupName: 'sharedinfra'
            resourcePrefix: 'hmiapim'
            terraformVersion: '0.13.3'
        - ${{ if or(eq("${parameters.deployTo", "all-services"}), eq("${parameters.deployTo", "SharedServies"}))}}:
          - name: SharedServies
            displayName: 'Shared Services'
            resourceGroupName: 'sharedservices-state'
            resourcePrefix: 'hmiss'
            terraformVersion: '0.15.4'

  - template: pipeline/stages/apply.yaml
    parameters:
      environments:
        - name: sbox
          subscription: DTS-SHAREDSERVICES-SBOX
          dependency: 'CIBuild'
        - name: dev
          subscription: DTS-SHAREDSERVICES-DEV
          dependency: 'sbox'
        - name: test
          subscription: DTS-SHAREDSERVICES-TEST
          dependency: 'dev'
        - name: stg
          subscription: DTS-SHAREDSERVICES-STG
          dependency: 'test'
        - name: prod
          subscription: DTS-SHAREDSERVICES-PROD
          dependency: 'stg'
      services: 
        - ${{ if or(eq(parameters.deployTo, "all-services"}), eq(parameters.deployTo, "SharedInfra"}))}}:
          - name: SharedInfra
            displayName: 'Shared Infrastructure'
            resourceGroupName: 'sharedinfra'
            resourcePrefix: 'hmiapim'
            terraformVersion: '0.13.3'
        - ${{ if or(eq(parameters.deployTo, "all-services"}), eq(parameters.deployTo, "SharedServies"}))}}:
          - name: SharedServies
            displayName: 'Shared Services'
            resourceGroupName: 'sharedservices-state'
            resourcePrefix: 'hmiss'
            terraformVersion: '0.15.4'

