trigger:
  - master
pr:
  - none

resources:
  repositories:
    - repository: azTemplates
      type: github
      name: hmcts/azure-devops-templates
      ref: refs/heads/group-fixes
      endpoint: hmcts

parameters:
  - name: deployTo
    displayName: Services to Deploy (All default)
    type: string
    default: all-services
    values:
      - all-services
      - SharedInfra
      - SharedServies        

variables:
  - group: HMI-APIM-Common
  - name: product
    value: 'hmi'
  - name: businessArea
    value: 'Cross-Cutting'
  - name: builtFrom
    value: $(Build.Repository.Name)
  - name: application
    value: 'hearing-management-interface'

stages:

  - stage: CIBuild
    displayName: 'CI Build Application'
    jobs:
      - template: pipeline/jobs/terraform-validate.yaml
        parameters:
          displayName: "Validate Terraform files"

  - template: pipeline/stages/plan.yaml
    parameters:
      template: pipeline/variables/deployment-parameters.yaml

  - template: pipeline/stages/wait.yaml
    parameters:
      template: pipeline/variables/deployment-parameters.yaml

  - template: pipeline/stages/apply.yaml
    parameters:
      template: pipeline/variables/deployment-parameters.yaml

