trigger:
  - master
pr:
  - master

resources:
  repositories:
    - repository: azTemplates
      type: github
      name: hmcts/azure-devops-templates
      ref: main
      endpoint: hmcts      

variables:
  - group: HMI-APIM-Common
  - name: product
    value: 'hmi'
  - name: businessArea
    value: 'cross-cutting'
  - name: builtFrom
    value: $(Build.Repository.Name)
  - name: application
    value: 'hearings-management-interface'

stages:

  - stage: CIBuild
    displayName: 'CI Build Application'
    jobs:
      - template: pipeline/jobs/terraform-validate.yaml
        parameters:
          terraformPath: $(Build.SourcesDirectory)/terraform

## NOTE: 
## The Environments and Services parameters below are duplicated
## This is due to limitations on AzDO Pipelines setting parameter templates and/or non-runtime parameters and/or object type variables.
## If you change one, be sure to change all others below.

  - template: pipeline/stages/plan.yaml
    parameters:
      environments:
        - name: sbox
          subscription: DTS-SHAREDSERVICES-SBOX
          dependency: 'CIBuild'
        - name: dev
          subscription: DTS-SHAREDSERVICES-DEV
          dependency: 'sbox'
        - name: test
          subscription: DTS-SHAREDSERVICES-TEST
          dependency: 'dev'
        - name: ithc
          subscription: DTS-SHAREDSERVICES-ITHC
          dependency: 'dev'
        - name: stg
          subscription: DTS-SHAREDSERVICES-STG
          dependency: 'test'
        - name: prod
          subscription: DTS-SHAREDSERVICES-PROD
          dependency: 'stg'

  - template: pipeline/stages/wait.yaml
    parameters:
      environments:
        - name: sbox
          subscription: DTS-SHAREDSERVICES-SBOX
          dependency: 'CIBuild'
        - name: dev
          subscription: DTS-SHAREDSERVICES-DEV
          dependency: 'sbox'
        - name: test
          subscription: DTS-SHAREDSERVICES-TEST
          dependency: 'dev'
        - name: ithc
          subscription: DTS-SHAREDSERVICES-ITHC
          dependency: 'dev'
        - name: stg
          subscription: DTS-SHAREDSERVICES-STG
          dependency: 'test'
        - name: prod
          subscription: DTS-SHAREDSERVICES-PROD
          dependency: 'stg'

  - template: pipeline/stages/apply.yaml
    parameters:
      environments:
        - name: sbox
          subscription: DTS-SHAREDSERVICES-SBOX
          dependency: 'CIBuild'
        - name: dev
          subscription: DTS-SHAREDSERVICES-DEV
          dependency: 'sbox'
        - name: test
          subscription: DTS-SHAREDSERVICES-TEST
          dependency: 'dev'
        - name: ithc
          subscription: DTS-SHAREDSERVICES-ITHC
          dependency: 'dev'
        - name: stg
          subscription: DTS-SHAREDSERVICES-STG
          dependency: 'test'
        - name: prod
          subscription: DTS-SHAREDSERVICES-PROD
          dependency: 'stg'

