variable "environment" {}
variable "resource_group" {}
variable "product" {}
variable "location" {}
variable "address_space" {}
variable "tags" {}
variable "subnet_address_prefixes" {}
variable "service_endpoints" {}
variable "subnet_delegation" {}
variable "apim_nsg_rules" {}
variable "apim_rules" {}
variable "route_name" {}
variable "route_address_prefix" {}
variable "route_next_hop_type" {}
variable "next_hop_in_ip_address" {}