parameters:
  environments:
    - name: sbox
      subscription: DTS-SHAREDSERVICES-SBOX
      dependency: 'CIBuild'
    - name: dev
      subscription: DTS-SHAREDSERVICES-DEV
      dependency: 'sbox'
    - name: test
      subscription: DTS-SHAREDSERVICES-TEST
      dependency: 'dev'
    - name: stg
      subscription: DTS-SHAREDSERVICES-STG
      dependency: 'test'
    - name: prod
      subscription: DTS-SHAREDSERVICES-PROD
      dependency: 'stg'
  services: 
      - ${{ if or(eq("${parameters.deployTo", "all-services"}), eq("${parameters.deployTo", "SharedInfra"}))}}:
        - name: SharedInfra
          displayName: 'Shared Infrastructure'
          resourceGroupName: 'sharedinfra'
          resourcePrefix: 'hmiapim'
          terraformVersion: '0.13.3'
      - ${{ if or(eq("${parameters.deployTo", "all-services"}), eq("${parameters.deployTo", "SharedServies"}))}}:
        - name: SharedServies
          displayName: 'Shared Services'
          resourceGroupName: 'sharedservices-state'
          resourcePrefix: 'hmiss'
          terraformVersion: '0.15.4'